CREATE TABLE db_mypresskit.dj
(
    ID int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRST_NAME varchar(80),
    LAST_NAME varchar(80),
    EMAIL varchar(100),
    ALSO_KNOWN_AS varchar(100),
    SOUNDCLOUD varchar(100),
    MIXCLOUD varchar(100),
    FACEBOOK varchar(100),
    PICTURE varchar(100),
    VIEWED int(11)
);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (102, 'Test Dj 0', 'Last Name0', 'a@c.0', 'CX-0', 'SoundCloud0', 'MixCloud0', 'facebook0', 'Path to pic0', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (103, 'Test Dj 1', 'Last Name1', 'a@c.1', 'CX-1', 'SoundCloud1', 'MixCloud1', 'facebook1', 'Path to pic1', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (104, 'Test Dj 2', 'Last Name2', 'a@c.2', 'CX-2', 'SoundCloud2', 'MixCloud2', 'facebook2', 'Path to pic2', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (105, 'Test Dj 3', 'Last Name3', 'a@c.3', 'CX-3', 'SoundCloud3', 'MixCloud3', 'facebook3', 'Path to pic3', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (106, 'Test Dj 4', 'Last Name4', 'a@c.4', 'CX-4', 'SoundCloud4', 'MixCloud4', 'facebook4', 'Path to pic4', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (107, 'Test Dj 5', 'Last Name5', 'a@c.5', 'CX-5', 'SoundCloud5', 'MixCloud5', 'facebook5', 'Path to pic5', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (108, 'Test Dj 6', 'Last Name6', 'a@c.6', 'CX-6', 'SoundCloud6', 'MixCloud6', 'facebook6', 'Path to pic6', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (109, 'Test Dj 7', 'Last Name7', 'a@c.7', 'CX-7', 'SoundCloud7', 'MixCloud7', 'facebook7', 'Path to pic7', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (110, 'Test Dj 8', 'Last Name8', 'a@c.8', 'CX-8', 'SoundCloud8', 'MixCloud8', 'facebook8', 'Path to pic8', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (111, 'Test Dj 9', 'Last Name9', 'a@c.9', 'CX-9', 'SoundCloud9', 'MixCloud9', 'facebook9', 'Path to pic9', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (112, 'Test Dj 10', 'Last Name10', 'a@c.10', 'CX-10', 'SoundCloud10', 'MixCloud10', 'facebook10', 'Path to pic10', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (113, 'Test Dj 11', 'Last Name11', 'a@c.11', 'CX-11', 'SoundCloud11', 'MixCloud11', 'facebook11', 'Path to pic11', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (114, 'Test Dj 12', 'Last Name12', 'a@c.12', 'CX-12', 'SoundCloud12', 'MixCloud12', 'facebook12', 'Path to pic12', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (115, 'Test Dj 13', 'Last Name13', 'a@c.13', 'CX-13', 'SoundCloud13', 'MixCloud13', 'facebook13', 'Path to pic13', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (116, 'Test Dj 14', 'Last Name14', 'a@c.14', 'CX-14', 'SoundCloud14', 'MixCloud14', 'facebook14', 'Path to pic14', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (117, 'Test Dj 15', 'Last Name15', 'a@c.15', 'CX-15', 'SoundCloud15', 'MixCloud15', 'facebook15', 'Path to pic15', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (118, 'Test Dj 16', 'Last Name16', 'a@c.16', 'CX-16', 'SoundCloud16', 'MixCloud16', 'facebook16', 'Path to pic16', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (119, 'Test Dj 17', 'Last Name17', 'a@c.17', 'CX-17', 'SoundCloud17', 'MixCloud17', 'facebook17', 'Path to pic17', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (120, 'Test Dj 18', 'Last Name18', 'a@c.18', 'CX-18', 'SoundCloud18', 'MixCloud18', 'facebook18', 'Path to pic18', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (121, 'Test Dj 19', 'Last Name19', 'a@c.19', 'CX-19', 'SoundCloud19', 'MixCloud19', 'facebook19', 'Path to pic19', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (122, 'Test Dj 20', 'Last Name20', 'a@c.20', 'CX-20', 'SoundCloud20', 'MixCloud20', 'facebook20', 'Path to pic20', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (123, 'Test Dj 21', 'Last Name21', 'a@c.21', 'CX-21', 'SoundCloud21', 'MixCloud21', 'facebook21', 'Path to pic21', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (124, 'Test Dj 22', 'Last Name22', 'a@c.22', 'CX-22', 'SoundCloud22', 'MixCloud22', 'facebook22', 'Path to pic22', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (125, 'Test Dj 23', 'Last Name23', 'a@c.23', 'CX-23', 'SoundCloud23', 'MixCloud23', 'facebook23', 'Path to pic23', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (126, 'Test Dj 24', 'Last Name24', 'a@c.24', 'CX-24', 'SoundCloud24', 'MixCloud24', 'facebook24', 'Path to pic24', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (127, 'Test Dj 25', 'Last Name25', 'a@c.25', 'CX-25', 'SoundCloud25', 'MixCloud25', 'facebook25', 'Path to pic25', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (128, 'Test Dj 26', 'Last Name26', 'a@c.26', 'CX-26', 'SoundCloud26', 'MixCloud26', 'facebook26', 'Path to pic26', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (129, 'Test Dj 27', 'Last Name27', 'a@c.27', 'CX-27', 'SoundCloud27', 'MixCloud27', 'facebook27', 'Path to pic27', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (130, 'Test Dj 28', 'Last Name28', 'a@c.28', 'CX-28', 'SoundCloud28', 'MixCloud28', 'facebook28', 'Path to pic28', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (131, 'Test Dj 29', 'Last Name29', 'a@c.29', 'CX-29', 'SoundCloud29', 'MixCloud29', 'facebook29', 'Path to pic29', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (132, 'Test Dj 30', 'Last Name30', 'a@c.30', 'CX-30', 'SoundCloud30', 'MixCloud30', 'facebook30', 'Path to pic30', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (133, 'Test Dj 31', 'Last Name31', 'a@c.31', 'CX-31', 'SoundCloud31', 'MixCloud31', 'facebook31', 'Path to pic31', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (134, 'Test Dj 32', 'Last Name32', 'a@c.32', 'CX-32', 'SoundCloud32', 'MixCloud32', 'facebook32', 'Path to pic32', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (135, 'Test Dj 33', 'Last Name33', 'a@c.33', 'CX-33', 'SoundCloud33', 'MixCloud33', 'facebook33', 'Path to pic33', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (136, 'Test Dj 34', 'Last Name34', 'a@c.34', 'CX-34', 'SoundCloud34', 'MixCloud34', 'facebook34', 'Path to pic34', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (137, 'Test Dj 35', 'Last Name35', 'a@c.35', 'CX-35', 'SoundCloud35', 'MixCloud35', 'facebook35', 'Path to pic35', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (138, 'Test Dj 36', 'Last Name36', 'a@c.36', 'CX-36', 'SoundCloud36', 'MixCloud36', 'facebook36', 'Path to pic36', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (139, 'Test Dj 37', 'Last Name37', 'a@c.37', 'CX-37', 'SoundCloud37', 'MixCloud37', 'facebook37', 'Path to pic37', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (140, 'Test Dj 38', 'Last Name38', 'a@c.38', 'CX-38', 'SoundCloud38', 'MixCloud38', 'facebook38', 'Path to pic38', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (141, 'Test Dj 39', 'Last Name39', 'a@c.39', 'CX-39', 'SoundCloud39', 'MixCloud39', 'facebook39', 'Path to pic39', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (142, 'Test Dj 40', 'Last Name40', 'a@c.40', 'CX-40', 'SoundCloud40', 'MixCloud40', 'facebook40', 'Path to pic40', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (143, 'Test Dj 41', 'Last Name41', 'a@c.41', 'CX-41', 'SoundCloud41', 'MixCloud41', 'facebook41', 'Path to pic41', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (144, 'Test Dj 42', 'Last Name42', 'a@c.42', 'CX-42', 'SoundCloud42', 'MixCloud42', 'facebook42', 'Path to pic42', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (145, 'Test Dj 43', 'Last Name43', 'a@c.43', 'CX-43', 'SoundCloud43', 'MixCloud43', 'facebook43', 'Path to pic43', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (146, 'Test Dj 44', 'Last Name44', 'a@c.44', 'CX-44', 'SoundCloud44', 'MixCloud44', 'facebook44', 'Path to pic44', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (147, 'Test Dj 45', 'Last Name45', 'a@c.45', 'CX-45', 'SoundCloud45', 'MixCloud45', 'facebook45', 'Path to pic45', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (148, 'Test Dj 46', 'Last Name46', 'a@c.46', 'CX-46', 'SoundCloud46', 'MixCloud46', 'facebook46', 'Path to pic46', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (149, 'Test Dj 47', 'Last Name47', 'a@c.47', 'CX-47', 'SoundCloud47', 'MixCloud47', 'facebook47', 'Path to pic47', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (150, 'Test Dj 48', 'Last Name48', 'a@c.48', 'CX-48', 'SoundCloud48', 'MixCloud48', 'facebook48', 'Path to pic48', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (151, 'Test Dj 49', 'Last Name49', 'a@c.49', 'CX-49', 'SoundCloud49', 'MixCloud49', 'facebook49', 'Path to pic49', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (152, 'Test Dj 50', 'Last Name50', 'a@c.50', 'CX-50', 'SoundCloud50', 'MixCloud50', 'facebook50', 'Path to pic50', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (153, 'Test Dj 51', 'Last Name51', 'a@c.51', 'CX-51', 'SoundCloud51', 'MixCloud51', 'facebook51', 'Path to pic51', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (154, 'Test Dj 52', 'Last Name52', 'a@c.52', 'CX-52', 'SoundCloud52', 'MixCloud52', 'facebook52', 'Path to pic52', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (155, 'Test Dj 53', 'Last Name53', 'a@c.53', 'CX-53', 'SoundCloud53', 'MixCloud53', 'facebook53', 'Path to pic53', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (156, 'Test Dj 54', 'Last Name54', 'a@c.54', 'CX-54', 'SoundCloud54', 'MixCloud54', 'facebook54', 'Path to pic54', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (157, 'Test Dj 55', 'Last Name55', 'a@c.55', 'CX-55', 'SoundCloud55', 'MixCloud55', 'facebook55', 'Path to pic55', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (158, 'Test Dj 56', 'Last Name56', 'a@c.56', 'CX-56', 'SoundCloud56', 'MixCloud56', 'facebook56', 'Path to pic56', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (159, 'Test Dj 57', 'Last Name57', 'a@c.57', 'CX-57', 'SoundCloud57', 'MixCloud57', 'facebook57', 'Path to pic57', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (160, 'Test Dj 58', 'Last Name58', 'a@c.58', 'CX-58', 'SoundCloud58', 'MixCloud58', 'facebook58', 'Path to pic58', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (161, 'Test Dj 59', 'Last Name59', 'a@c.59', 'CX-59', 'SoundCloud59', 'MixCloud59', 'facebook59', 'Path to pic59', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (162, 'Test Dj 60', 'Last Name60', 'a@c.60', 'CX-60', 'SoundCloud60', 'MixCloud60', 'facebook60', 'Path to pic60', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (163, 'Test Dj 61', 'Last Name61', 'a@c.61', 'CX-61', 'SoundCloud61', 'MixCloud61', 'facebook61', 'Path to pic61', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (164, 'Test Dj 62', 'Last Name62', 'a@c.62', 'CX-62', 'SoundCloud62', 'MixCloud62', 'facebook62', 'Path to pic62', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (165, 'Test Dj 63', 'Last Name63', 'a@c.63', 'CX-63', 'SoundCloud63', 'MixCloud63', 'facebook63', 'Path to pic63', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (166, 'Test Dj 64', 'Last Name64', 'a@c.64', 'CX-64', 'SoundCloud64', 'MixCloud64', 'facebook64', 'Path to pic64', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (167, 'Test Dj 65', 'Last Name65', 'a@c.65', 'CX-65', 'SoundCloud65', 'MixCloud65', 'facebook65', 'Path to pic65', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (168, 'Test Dj 66', 'Last Name66', 'a@c.66', 'CX-66', 'SoundCloud66', 'MixCloud66', 'facebook66', 'Path to pic66', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (169, 'Test Dj 67', 'Last Name67', 'a@c.67', 'CX-67', 'SoundCloud67', 'MixCloud67', 'facebook67', 'Path to pic67', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (170, 'Test Dj 68', 'Last Name68', 'a@c.68', 'CX-68', 'SoundCloud68', 'MixCloud68', 'facebook68', 'Path to pic68', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (171, 'Test Dj 69', 'Last Name69', 'a@c.69', 'CX-69', 'SoundCloud69', 'MixCloud69', 'facebook69', 'Path to pic69', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (172, 'Test Dj 70', 'Last Name70', 'a@c.70', 'CX-70', 'SoundCloud70', 'MixCloud70', 'facebook70', 'Path to pic70', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (173, 'Test Dj 71', 'Last Name71', 'a@c.71', 'CX-71', 'SoundCloud71', 'MixCloud71', 'facebook71', 'Path to pic71', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (174, 'Test Dj 72', 'Last Name72', 'a@c.72', 'CX-72', 'SoundCloud72', 'MixCloud72', 'facebook72', 'Path to pic72', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (175, 'Test Dj 73', 'Last Name73', 'a@c.73', 'CX-73', 'SoundCloud73', 'MixCloud73', 'facebook73', 'Path to pic73', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (176, 'Test Dj 74', 'Last Name74', 'a@c.74', 'CX-74', 'SoundCloud74', 'MixCloud74', 'facebook74', 'Path to pic74', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (177, 'Test Dj 75', 'Last Name75', 'a@c.75', 'CX-75', 'SoundCloud75', 'MixCloud75', 'facebook75', 'Path to pic75', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (178, 'Test Dj 76', 'Last Name76', 'a@c.76', 'CX-76', 'SoundCloud76', 'MixCloud76', 'facebook76', 'Path to pic76', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (179, 'Test Dj 77', 'Last Name77', 'a@c.77', 'CX-77', 'SoundCloud77', 'MixCloud77', 'facebook77', 'Path to pic77', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (180, 'Test Dj 78', 'Last Name78', 'a@c.78', 'CX-78', 'SoundCloud78', 'MixCloud78', 'facebook78', 'Path to pic78', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (181, 'Test Dj 79', 'Last Name79', 'a@c.79', 'CX-79', 'SoundCloud79', 'MixCloud79', 'facebook79', 'Path to pic79', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (182, 'Test Dj 80', 'Last Name80', 'a@c.80', 'CX-80', 'SoundCloud80', 'MixCloud80', 'facebook80', 'Path to pic80', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (183, 'Test Dj 81', 'Last Name81', 'a@c.81', 'CX-81', 'SoundCloud81', 'MixCloud81', 'facebook81', 'Path to pic81', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (184, 'Test Dj 82', 'Last Name82', 'a@c.82', 'CX-82', 'SoundCloud82', 'MixCloud82', 'facebook82', 'Path to pic82', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (185, 'Test Dj 83', 'Last Name83', 'a@c.83', 'CX-83', 'SoundCloud83', 'MixCloud83', 'facebook83', 'Path to pic83', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (186, 'Test Dj 84', 'Last Name84', 'a@c.84', 'CX-84', 'SoundCloud84', 'MixCloud84', 'facebook84', 'Path to pic84', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (187, 'Test Dj 85', 'Last Name85', 'a@c.85', 'CX-85', 'SoundCloud85', 'MixCloud85', 'facebook85', 'Path to pic85', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (188, 'Test Dj 86', 'Last Name86', 'a@c.86', 'CX-86', 'SoundCloud86', 'MixCloud86', 'facebook86', 'Path to pic86', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (189, 'Test Dj 87', 'Last Name87', 'a@c.87', 'CX-87', 'SoundCloud87', 'MixCloud87', 'facebook87', 'Path to pic87', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (190, 'Test Dj 88', 'Last Name88', 'a@c.88', 'CX-88', 'SoundCloud88', 'MixCloud88', 'facebook88', 'Path to pic88', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (191, 'Test Dj 89', 'Last Name89', 'a@c.89', 'CX-89', 'SoundCloud89', 'MixCloud89', 'facebook89', 'Path to pic89', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (192, 'Test Dj 90', 'Last Name90', 'a@c.90', 'CX-90', 'SoundCloud90', 'MixCloud90', 'facebook90', 'Path to pic90', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (193, 'Test Dj 91', 'Last Name91', 'a@c.91', 'CX-91', 'SoundCloud91', 'MixCloud91', 'facebook91', 'Path to pic91', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (194, 'Test Dj 92', 'Last Name92', 'a@c.92', 'CX-92', 'SoundCloud92', 'MixCloud92', 'facebook92', 'Path to pic92', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (195, 'Test Dj 93', 'Last Name93', 'a@c.93', 'CX-93', 'SoundCloud93', 'MixCloud93', 'facebook93', 'Path to pic93', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (196, 'Test Dj 94', 'Last Name94', 'a@c.94', 'CX-94', 'SoundCloud94', 'MixCloud94', 'facebook94', 'Path to pic94', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (197, 'Test Dj 95', 'Last Name95', 'a@c.95', 'CX-95', 'SoundCloud95', 'MixCloud95', 'facebook95', 'Path to pic95', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (198, 'Test Dj 96', 'Last Name96', 'a@c.96', 'CX-96', 'SoundCloud96', 'MixCloud96', 'facebook96', 'Path to pic96', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (199, 'Test Dj 97', 'Last Name97', 'a@c.97', 'CX-97', 'SoundCloud97', 'MixCloud97', 'facebook97', 'Path to pic97', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (200, 'Test Dj 98', 'Last Name98', 'a@c.98', 'CX-98', 'SoundCloud98', 'MixCloud98', 'facebook98', 'Path to pic98', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (201, 'Test Dj 99', 'Last Name99', 'a@c.99', 'CX-99', 'SoundCloud99', 'MixCloud99', 'facebook99', 'Path to pic99', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (202, 'Test Dj 100', 'Last Name100', 'a@c.100', 'CX-100', 'SoundCloud100', 'MixCloud100', 'facebook100', 'Path to pic100', 1);
INSERT INTO db_mypresskit.dj (ID, FIRST_NAME, LAST_NAME, EMAIL, ALSO_KNOWN_AS, SOUNDCLOUD, MIXCLOUD, FACEBOOK, PICTURE, VIEWED) VALUES (203, 'Israel', 'Desde postman', 'a@postman.0', 'CX-0', 'SoundCloud0', 'MixCloud0', 'facebook0', 'Path to pic0', 1);